# Generated by Django 5.1.6 on 2025-02-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opening_hours', models.TextField()),
                ('entrance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('website', models.URLField(blank=True)),
                ('popularity_score', models.FloatField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.CreateModel(
            name='TouristSpotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tourist spot categories',
            },
        ),
    ]
