# Generated by Django 5.1.6 on 2025-02-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_spots', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourist_spots.touristspotcategory'),
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['popularity_score'], name='tourist_spo_popular_b17592_idx'),
        ),
    ]
