# Generated by Django 5.1.6 on 2025-02-22 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('auto', 'Automatique')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('elec', 'Électrique')], max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_start', models.DateField()),
                ('available_end', models.DateField()),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['price_per_day'], name='vehicles_ve_price_p_b29e1b_idx'), models.Index(fields=['available_start', 'available_end'], name='vehicles_ve_availab_697ab2_idx')],
            },
        ),
    ]
